create table member (
    id         uuid not null,
    name       varchar(255),
    email      varchar(255),
    password   varchar(255),
    is_valid   boolean not null,
    created_at timestamp(6) not null,
    created_by uuid,
    updated_at timestamp(6) not null,
    updated_by uuid,
    deleted_at timestamp(6),
    deleted_by uuid,
    is_deleted boolean not null,
    primary key (id),
    constraint uk_member_email unique (email)
);

create table member_role (
    member_id uuid not null,
    role      varchar(255) check (role in ('MEMBER', 'ADMIN')),
    constraint fk_member_role_member foreign key (member_id) references member (id)
);

create table outbox_event (
    id            bigint generated by default as identity,
    topic         varchar(255) not null,
    message_key   varchar(255),
    payload_type  varchar(255) not null,
    payload       varchar(65535) not null,
    trace_headers varchar(65535),
    created_at    timestamp(6) with time zone not null,
    failed_at     timestamp(6) with time zone,
    primary key (id)
);
