plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'modu-drive'

include ("common:core")
include ("common:api")
include ("common:infrastructure:jpa")
include ("common:infrastructure:resilience4j")
include ("common:infrastructure:spring-cloud")

include ("services:eureka-server")
include ("services:gateway-service")
include ("services:member-service")
include ("services:auth-service")
include ("services:file-service")
