import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage

plugins {
    id 'com.bmuschko.docker-remote-api' version '10.0.0'
}

group = 'com.modudrive.gateway'
version = '0.0.1-SNAPSHOT'

dependencies {
    implementation project(':common:core')
    implementation project(':common:api')
    implementation project(':common:infrastructure:resilience4j')

    implementation 'org.springframework.cloud:spring-cloud-starter-gateway-server-webflux'
    implementation 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-reactor-resilience4j'
    implementation 'org.springframework.boot:spring-boot-starter-webclient'
    implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:3.0.3'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
}

task prepareDockerContext(type: Copy) {
    dependsOn bootJar
    from bootJar
    from rootProject.file('.docker/Dockerfile')
    into layout.buildDirectory.dir('docker')
}

task docker(type: DockerBuildImage) {
    dependsOn prepareDockerContext
    inputDir = layout.buildDirectory.dir('docker')
    images.add("${rootProject.name}-${project.name}:${version}")
    buildArgs = ['JAR_FILE': bootJar.archiveFileName.get()]
}
