-- Messages this service already handled, so an SQS redelivery past its 5-minute dedup window doesn't
-- repeat the effect. Written in the same transaction as the business change; purged after 7 days.
create table processed_event (
    id               bigint generated by default as identity,
    queue_name       varchar(255) not null,
    deduplication_id varchar(255) not null,
    processed_at     timestamp(6) with time zone not null,
    primary key (id),
    constraint uk_processed_event unique (queue_name, deduplication_id)
);

create index processed_event_processed_at_idx on processed_event (processed_at);
