spring:
  application:
    name: file-service
  config:
    import:
      - "classpath:application-jpa.yml"
      - "classpath:application-resilience4j.yml"
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

modudrive:
  file:
    default-quota-bytes: ${MODUDRIVE_FILE_DEFAULT_QUOTA_BYTES}

resilience4j:
  retry:
    instances:
      memberServiceRetry:
        baseConfig: default
  circuitbreaker:
    instances:
      memberServiceCircuitBreaker:
        baseConfig: default
