spring:
  application:
    name: file-service
  config:
    import:
      - "classpath:application-jpa.yml"
      - "classpath:application-resilience4j.yml"

modudrive:
  file:
    default-quota-bytes: ${MODUDRIVE_FILE_DEFAULT_QUOTA_BYTES}
