spring:
  application:
    name: mail-service
  config:
    import:
      - "classpath:application-observability.yml"
      - "classpath:application-redis.yml"
      - "classpath:application-sqs.yml"
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

modudrive:
  mail:
    from: ${MAIL_FROM}

client:
  url: ${CLIENT_URL}
