spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allow-credentials: true
                allowed-origins: ${client.url}
                allowed-headers: "*"
                allowed-methods:
                  - PUT
                  - PATCH
                  - GET
                  - POST
                  - DELETE
                  - OPTIONS

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 15s
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 10s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        record-exceptions:
          - java.util.concurrent.TimeoutException
          - org.springframework.cloud.gateway.support.NotFoundException
          - io.netty.channel.AbstractChannel$AnnotatedConnectException
    instances:
      memberServiceCircuitBreaker:
        baseConfig: default
      authServiceCircuitBreaker:
        baseConfig: default
      fileServiceCircuitBreaker:
        baseConfig: default
      storageServiceCircuitBreaker:
        baseConfig: default
      notificationServiceCircuitBreaker:
        baseConfig: default

client:
  url: ${FRONTEND_APP_URL}
