-- Devices each member verified by email (spec 004 2-2). Only the device id's SHA-256 is kept, so a
-- leaked table can't be turned back into a working device cookie. A device counts as known while
-- last_used_at is within 90 days.
create table known_device (
    member_id    uuid not null,
    device_hash  varchar(64) not null,
    created_at   timestamp(6) with time zone not null,
    last_used_at timestamp(6) with time zone not null,
    primary key (member_id, device_hash)
);

-- Transactional outbox (common:infrastructure:messaging) — the same shape member/file-service reach
-- through their V1..V5/V6.
create table outbox_event (
    id             bigint generated by default as identity,
    queue          varchar(255) not null,
    message_key    varchar(255),
    payload_type   varchar(255) not null,
    payload        varchar(65535) not null,
    trace_headers  varchar(65535),
    created_at     timestamp(6) with time zone not null,
    status         varchar(255) not null,
    sent_at        timestamp(6) with time zone,
    failed_at      timestamp(6) with time zone,
    failure_reason varchar(1000),
    primary key (id),
    constraint outbox_event_status_check check (status in ('PENDING', 'SENT', 'FAILED'))
);

create index outbox_event_pending_idx on outbox_event (id) where status = 'PENDING';
create index outbox_event_sent_at_idx on outbox_event (sent_at) where status = 'SENT';
create index outbox_event_failed_idx on outbox_event (queue) where status = 'FAILED';
