name: modudrive-service

services:

  eureka-server:
    image: modu-drive-eureka-server:0.0.1-SNAPSHOT
    networks:
      - modudrive_network
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    environment:
      - SERVER_PORT=${EUREKA_SERVER_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:${EUREKA_SERVER_PORT}/eureka/

  gateway-service:
    image: modu-drive-gateway-service:0.0.1-SNAPSHOT
    networks:
      - modudrive_network
    ports:
      - "${GATEWAY_SERVER_PORT}:${GATEWAY_SERVER_PORT}"
    environment:
      - SERVER_PORT=${GATEWAY_SERVER_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
      - CLIENT_URL=${CLIENT_URL}
    depends_on:
      member-service:
        condition: service_started

  member-service:
    image: modu-drive-member-service:0.0.1-SNAPSHOT
    networks:
      - modudrive_network
    ports:
      - "${MEMBER_SERVER_PORT}:${MEMBER_SERVER_PORT}"
    environment:
      - SERVER_PORT=${MEMBER_SERVER_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - MEMBER_EMAIL_VERIFICATION_TOKEN_EXPIRATION=${MEMBER_EMAIL_VERIFICATION_TOKEN_EXPIRATION}
    depends_on:
      eureka-server:
        condition: service_started

  auth-service:
    image: modu-drive-auth-service:0.0.1-SNAPSHOT
    networks:
      - modudrive_network
    ports:
      - "${AUTH_SERVER_PORT}:${AUTH_SERVER_PORT}"
    environment:
      - SERVER_PORT=${AUTH_SERVER_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRATION=${JWT_ACCESS_TOKEN_EXPIRATION}
      - JWT_REFRESH_TOKEN_EXPIRATION=${JWT_REFRESH_TOKEN_EXPIRATION}
      - JWT_REFRESH_TOKEN_COOKIE_SECURE=${JWT_REFRESH_TOKEN_COOKIE_SECURE}
    depends_on:
      eureka-server:
        condition: service_started

  file-service:
    image: modu-drive-file-service:0.0.1-SNAPSHOT
    networks:
      - modudrive_network
    ports:
      - "${FILE_SERVER_PORT}:${FILE_SERVER_PORT}"
    environment:
      - SERVER_PORT=${FILE_SERVER_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - MODUDRIVE_FILE_DEFAULT_QUOTA_BYTES=${MODUDRIVE_FILE_DEFAULT_QUOTA_BYTES}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      eureka-server:
        condition: service_started

  storage-service:
    image: modu-drive-storage-service:0.0.1-SNAPSHOT
    networks:
      - modudrive_network
    ports:
      - "${STORAGE_SERVER_PORT}:${STORAGE_SERVER_PORT}"
    environment:
      - SERVER_PORT=${STORAGE_SERVER_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
      - STORAGE_MULTIPART_MAX_FILE_SIZE=${STORAGE_MULTIPART_MAX_FILE_SIZE}
      - STORAGE_MULTIPART_MAX_REQUEST_SIZE=${STORAGE_MULTIPART_MAX_REQUEST_SIZE}
      - MODUDRIVE_STORAGE_MAX_FILE_SIZE_BYTES=${MODUDRIVE_STORAGE_MAX_FILE_SIZE_BYTES}
      - STORAGE_S3_ENDPOINT=${STORAGE_S3_ENDPOINT}
      - STORAGE_S3_BUCKET=${STORAGE_S3_BUCKET}
      - STORAGE_S3_ACCESS_KEY=${MINIO_ROOT_USER}
      - STORAGE_S3_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - STORAGE_S3_REGION=${STORAGE_S3_REGION}
      - STORAGE_BLOCK_SIZE=${STORAGE_BLOCK_SIZE}
    depends_on:
      eureka-server:
        condition: service_started

  mail-service:
    image: modu-drive-mail-service:0.0.1-SNAPSHOT
    networks:
      - modudrive_network
    ports:
      - "${MAIL_SERVER_PORT}:${MAIL_SERVER_PORT}"
    environment:
      - SERVER_PORT=${MAIL_SERVER_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MODUDRIVE_MAIL_VERIFY_BASE_URL=${MODUDRIVE_MAIL_VERIFY_BASE_URL}
    depends_on:
      eureka-server:
        condition: service_started

networks:
  modudrive_network:
    external: true
    name: modudrive_network
