name: modudrive-infra

services:

  postgres:
    image: postgres:18-alpine
    networks:
      - modudrive_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=modu_drive
      - POSTGRES_USER=modudrive
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U modudrive -d modu_drive"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    networks:
      - modudrive_network
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  modudrive_network:
    name: modudrive_network
    driver: bridge

volumes:
  postgres_data:
  minio_data:
