spring:
  application:
    name: notification-service
  config:
    import:
      - "classpath:application-jpa.yml"
      - "classpath:application-observability.yml"
      - "classpath:application-kafka.yml"
  kafka:
    consumer:
      group-id: notification-service
      properties:
        spring.json.trusted.packages: com.moduDrive.common.event.notification
