create table namespace (
    id          uuid not null,
    user_id     uuid not null unique,
    root_path   varchar(255) not null,
    quota_bytes bigint not null,
    created_at  timestamp(6),
    created_by  uuid,
    updated_at  timestamp(6),
    updated_by  uuid,
    deleted_at  timestamp(6),
    deleted_by  uuid,
    is_deleted  boolean,
    primary key (id)
);

create table file (
    id                 uuid not null,
    namespace_id       uuid not null,
    owner_id           uuid not null,
    name               varchar(255) not null,
    path               varchar(255) not null,
    is_directory       boolean,
    file_size          bigint,
    current_version_id uuid,
    status             varchar(255) not null check (status in ('PENDING', 'UPLOADED', 'TRASHED', 'DELETED')),
    active_slot_name   varchar(255),
    access_scope       varchar(255) check (access_scope in ('RESTRICTED', 'LINK')),
    link_role          varchar(255) check (link_role in ('VIEWER', 'EDITOR')),
    trashed_at         timestamp(6),
    created_at         timestamp(6),
    created_by         uuid,
    updated_at         timestamp(6),
    updated_by         uuid,
    deleted_at         timestamp(6),
    deleted_by         uuid,
    is_deleted         boolean,
    primary key (id),
    constraint uk_file_namespace_path_active_name unique (namespace_id, path, active_slot_name)
);

create index ix_file_status_trashed_at on file (status, trashed_at);

create table file_version (
    id          uuid not null,
    file_id     uuid not null,
    s3_path     varchar(255) not null,
    block_count integer not null,
    file_size   bigint,
    created_at  timestamp(6),
    created_by  uuid,
    primary key (id)
);

create table file_share (
    id                  uuid not null,
    file_id             uuid not null,
    owner_id            uuid not null,
    shared_with_user_id uuid,
    grantee_email       varchar(255),
    token               uuid,
    granted_role        varchar(255) check (granted_role in ('VIEWER', 'EDITOR')),
    created_at          timestamp(6),
    created_by          uuid,
    primary key (id),
    constraint uk_file_share_file_user unique (file_id, shared_with_user_id),
    constraint uk_file_share_file_email unique (file_id, grantee_email),
    constraint uk_file_share_token unique (token)
);

create table file_access (
    id          uuid not null,
    user_id     uuid not null,
    file_id     uuid not null,
    accessed_at timestamp(6) not null,
    created_at  timestamp(6),
    created_by  uuid,
    primary key (id),
    constraint uk_file_access_user_file unique (user_id, file_id)
);

create table file_favorite (
    id         uuid not null,
    user_id    uuid not null,
    file_id    uuid not null,
    created_at timestamp(6),
    created_by uuid,
    primary key (id),
    constraint uk_file_favorite_user_file unique (user_id, file_id)
);

create table outbox_event (
    id            bigint generated by default as identity,
    topic         varchar(255) not null,
    message_key   varchar(255),
    payload_type  varchar(255) not null,
    payload       varchar(65535) not null,
    trace_headers varchar(65535),
    created_at    timestamp(6) with time zone not null,
    failed_at     timestamp(6) with time zone,
    primary key (id)
);

-- ShedLock's own table (JdbcTemplateLockProvider); columns follow ShedLock's Postgres DDL.
create table shedlock (
    name       varchar(64) not null,
    lock_until timestamp(6) with time zone not null,
    locked_at  timestamp(6) with time zone not null,
    locked_by  varchar(255) not null,
    primary key (name)
);
