group = 'com.modudrive.common.infrastructure.resilience4j'

repositories {
    mavenCentral()
}

dependencies {
    api 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j'

    implementation project(':common:core')
}

bootRun {
    enabled = false
}

bootJar {
    enabled = false
}

bootBuildImage{
    enabled = false
}
